### ISSUE TITLE
Storage Token Permission Issue

### ISSUE THREAD

**Issue by isamllr** [Azure/azure-mobile-apps-net-files-server#18]
Hello, 
I am having troubles to push files to blob storage. The containers are being created and the SQL database is getting populated. The solution has been working but since we extended the model to store some more data, the issue appeared.

- Exchanging the Blob Storage (Classic to a newer one has not been working out.)
- Double checked Storage Connection String in the App Service

I updated all nugets to the latest preview versions, but since it did not help either and I only received a slightly different error message, I rolled back

**Versions:**
Server:
Microsoft.Azure.Mobile.Server: 1.1.157.1
Microsoft.Azure.Server.Files: 1.0.0.-beta-2
WindowsAzure.Storage 7.0.2-preview

Client:
Microsoft.Azure.Mobile.Client 2.0.1
Microsoft.Azure.Mobile.Client.Files 1.0.0.-beta-2
Microsoft.Azure.Mobile.Client.SQLiteStore 2.0.1

and

Server: 
WindowsAzure.Storage 7.2.0
Microsoft.Azure.Mobile.Server: 1.1.157.1
Microsoft.Azure.Server.Files: 1.0.0.-beta-2

Client:
Microsoft.Azure.Mobile.Client 2.1.1
Microsoft.Azure.Mobile.Client.SQLiteStore 2.1.1

Using an UWP & VS 2015 Update 3

**Log Stream:**
Module __DynamicModule_Microsoft.Owin.Host.SystemWeb.OwinHttpModule, Microsoft.Owin.Host.SystemWeb, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35_1f08a3ec-5ee5-48fe-a8ce-7c8d8d5c818c
Notification PreExecuteRequestHandler
Handler ExtensionlessUrlHandler-Integrated-4.0
Error Code 0x00000000
 
Requested URL **https://lqs:80/tables/DataFileDB/StorageToken**
Physical Path D:\home\site\wwwroot\tables\DataFileDB\StorageToken
Logon Method Anonymous 
Logon User Anonymous

**The request could not be understood by the server due to malformed syntax.** 

2016-08-17T15:28:27  PID[4512] Error       
Operation=JsonMediaTypeFormatter.ReadFromStreamAsync, Exception=Newtonsoft.Json.JsonSerializationException: Could not find member 'Permissions' on object of type 'DataFileDB'. Path 'Permissions', line 2, position 16.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2016-08-17T15:28:27  PID[4512] Error       
Operation=JsonMediaTypeFormatter.ReadFromStreamAsync, Exception=Newtonsoft.Json.JsonSerializationException: Could not find member 'TargetFile' on object of type 'DataFileDB'. Path 'TargetFile', line 3, position 15.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2016-08-17T15:28:27  PID[4512] Error       
Operation=JsonMediaTypeFormatter.ReadFromStreamAsync, Exception=Newtonsoft.Json.JsonSerializationException: Could not find member 'ScopedEntityId' on object of type 'DataFileDB'. Path 'ScopedEntityId', line 14, position 19.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2016-08-17T15:28:27  PID[4512] Error       
Operation=JsonMediaTypeFormatter.ReadFromStreamAsync, Exception=Newtonsoft.Json.JsonSerializationException: Could not find member 'ProviderName' on object of type 'DataFileDB'. Path 'ProviderName', line 15, position 17.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2016-08-17T15:28:27  PID[4512] Warning     
Message='UserMessage='The request is invalid.', ModelStateError=[item.Permissions=[An error has occurred.], item.TargetFile=[An error has occurred.], item.ScopedEntityId=[An error has occurred.], item.ProviderName=[An error has occurred.]]', Operation=ReflectedHttpActionDescriptor.ExecuteAsync, Status=400 (BadRequest), Exception=System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Microsoft.Azure.Mobile.Server.TableController`1.<InsertAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lqsService.Controllers.DataFileDBController.<PostDataFileDB>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
   
   ----------------------------------------------
   
   "   at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient.<ThrowInvalidResponse>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient.<SendRequestAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient.<RequestAsync>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.MobileServiceClient.<InternalInvokeApiAsync>d__69.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.MobileServiceClient.<InvokeApiAsync>d__63`2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.MobileServiceFilesClient.<GetStorageToken>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.MobileServiceFilesClient.<UploadFileAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.Operations.CreateMobileServiceFileOperation.<ExecuteOperation>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.Operations.MobileServiceFileOperation.<Execute>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.MobileServiceFileSyncContext.<PushChangesAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.MobileServiceSyncTableExtensions.<PushFileChangesAsync>d__7`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at KM_Application.Core.Models.Datahandling.<SyncAsync>d__11.MoveNext()"
   
Any ideas what could cause this issue?

**Comment by isamllr** [comment]
POST https://lqs.azurewebsites.net/tables/DataFileDB//StorageToken HTTP/1.1
Accept-Encoding: gzip
Accept: application/json
X-ZUMO-VERSION: ZUMO/2.1 (lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
X-ZUMO-FEATURES: AT
ZUMO-API-VERSION: 2.0.0
User-Agent: ZUMO/2.1 (lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
X-ZUMO-INSTALLATION-ID: 381cb9ba-18de-4bc5-bf36-ce5df5026bcd
Content-Length: 343
Content-Type: application/json; charset=utf-8
Host: lqs.azurewebsites.net
Connection: Keep-Alive

{
  "Permissions": "Write",
  "TargetFile": {
    "Id": "160713-152828-009",
    "Name": "160713-152828-009",
    "TableName": "DataFileDB",
    "ParentId": null,
    "Length": 0,
    "ContentMD5": null,
    "LastModified": null,
    "StoreUri": null,
    "Metadata": null
  },
  "ScopedEntityId": null,
  "ProviderName": null
}


HTTP/1.1 400 Bad Request
Content-Length: 239
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=369ae00d63a698f1d04f470d52cfcb2fac9357064d0f548d4de496e3bb4c0bc9;Path=/;Domain=lqs.azurewebsites.net
Date: Thu, 18 Aug 2016 11:02:20 GMT

{"message":"The request is invalid.","modelState":{"item.Permissions":["An error has occurred."],"item.TargetFile":["An error has occurred."],"item.ScopedEntityId":["An error has occurred."],"item.ProviderName":["An error has occurred."]}}

**Comment by lindydonna** [comment]
Are you trying to add new fields to the storage token itself?  Based on this error message, you're getting an error at the ASP.NET Web API serialization layer.

@pragnagopa Do you have any thoughts?

**Comment by isamllr** [comment]
Not that I know of, nothing changed really apart from my model (server, client, azure sql).

**Comment by fabiocav** [comment]
Is this the actual request captured from the application? Based on the URI pasted above, it does seem like you're missing the entity ID so the route is getting confused which explains the attempt to deserialize the payload as the entity type (DataFileDB), using 'StorageToken' as the id.

You mentioned you've made some changes to your model, as part of those changes, did you happen to introduce a base type and moved the ID property down to it? We did have a bug that was recently fixed that would fail to serialize the ID in those cases. The easy fix with the current bits is to move the ID to the actual type you're working with, if that is the case.

**Comment by fabiocav** [comment]
If you'd like to use the latest bits (with the ID fix in place), we've pushed packages to MyGet until we have a release:
o Nuget v3: https://www.myget.org/F/azure-mobile/api/v3/index.json 
o Nuget v2: https://www.myget.org/F/azure-mobile/api/v2

**Comment by lindydonna** [comment]
Btw, you can log your outgoing requests on the client to see if you're hitting the bug: https://github.com/Azure/azure-mobile-apps/wiki/Help,-my-app-isn't-working!#managed-client-xamarin-windows.

**Comment by isamllr** [comment]
@lindydonna Thanks for the hint, added logging, it's way more comfy this way, but I removed it again since it may have caused HTTP issues.
@fabiocav Using v3 now, still the same error. It's not clear to me why the entity Id is unavailable suddenly.

I am using 

        string id;
        [JsonProperty(PropertyName = "id")]
        public string Id
        {
            get { return id; }
            set { id = value; }
        }

for each client class having files attached, the server class does not have an Id but otherwise the same fields.

For the other classes without files,
public string Id { get; set; } 
does the job.

What should I go for with the latest nugets?


For some reason, using the v3 nuget (did not test v2) a lot of random http connection errors were happening. Multiple times of republishing the server when this happend helped - probably because of the restart of the mobile app.

Errors: Exception thrown: 'System.NullReferenceException' in Microsoft.WindowsAzure.Mobile.Files.Ext.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.ni.dll

Is there a way to update this Microsoft.WindowsAzure.Mobile.Files.Ext.dll? Does not seem to be part of the nugets.

**Comment by fabiocav** [comment]
V3 and V2 expose the same packages (the version here is just the Nuget endpoint version, you'd use one or the other based on the client).

I'm not sure I understand this:

> for each client class having files attached, the server class does not have an Id but otherwise the same fields.

The issue above would be triggered by the model defined on the client. Can you share the `DataFileDB` class you have on the client?

@pragnagopa do you know if we have an issue with the packages on MyGet that would explain this?

> Is there a way to update this Microsoft.WindowsAzure.Mobile.Files.Ext.dll? Does not seem to be part of the nugets.

**Comment by isamllr** [comment]
Client:

    public class DataFileDB
    {
        string id;
        [JsonProperty(PropertyName = "id")]
        public string Id
        {
            get { return id; }
            set { id = value; }
        }

        //instead of 
        //public string Id { get; set; }

        public string Unit_Id { get; set; }
        public string Company_Id { get; set; }
.
.
.
    }


Server:

using Microsoft.Azure.Mobile.Server;

namespace lqsService.DataObjects
{
    public class DataFileDB : EntityData
    {
        public string Unit_Id { get; set; }
        public string Company_Id { get; set; }
.
.
.
    }
}

**Comment by fabiocav** [comment]
@isamllr part of the bug I described above (which will be addressed in the next release) was an issue with casing. Could you either change the JsonProperty name casing to `Id` or remove the attribute to see if that helps?

**Comment by isamllr** [comment]
@fabiocav Can't seem to get past the System.Net.Http.HttpRequestException anymore, following up on Monday.

**Comment by pragnagopa** [comment]
@isamllr package on myget does install Microsoft.WindowsAzure.MobileServices.Files and Microsoft.WindowsAzure.MobileServices.Files.Ext. Tested with Xamarin.Android. Can you please try again?

**Comment by pragnagopa** [comment]
I was able to repro the issue. Looks like casing issue with Id. Will update myget with the fix soon.

**Comment by fabiocav** [comment]
@pragnagopa that's what I suspected. The core logic we looked at in the context of the `GetItemId` change deals with that, so it would be nice to make sure we're consistent with that.

**Comment by pragnagopa** [comment]
Updated packages in myget.

**Comment by isamllr** [comment]
@pragnagopa @fabiocav Thanks a lot, this helps a great deal! Keeping you posted.

**Comment by isamllr** [comment]
Having issues to build the app at all - the error is not affecting a project, but the entire solution.

Error	CA0001	CA0001 : An error was encountered while parsing IL for method: 'KM_Application.Core.Models.Datahandling+<SyncAsync>d__12.MoveNext', instruction at offset '0x6F' with opcode 'Callvirt'.

**Comment by pragnagopa** [comment]
@isamllr CA0001 is a CodeAnalysis error: https://msdn.microsoft.com/en-us/library/ms245246.aspx. Can you try disabling the CodeAnalysis?

**Comment by isamllr** [comment]
Thanks, can run the whole thing again.
The id-issue seems to be fixed, but now I am running into other stuff like

Request: GET https://lqs.azurewebsites.net/tables/DataFileDB/5f94574e-dea5-42b4-9aa2-66d7458c644f/MobileServiceFiles
HEADERS
X-ZUMO-FEATURES:AT
X-ZUMO-INSTALLATION-ID:381cb9ba-18de-4bc5-bf36-ce5df5026bcd
Accept:application/json
User-Agent:ZUMO/2.1,(lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
X-ZUMO-FEATURES:QS,OL
X-ZUMO-INSTALLATION-ID:381cb9ba-18de-4bc5-bf36-ce5df5026bcd
Accept:application/json
User-Agent:ZUMO/2.1,(lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
X-ZUMO-VERSION:ZUMO/2.1 (lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
X-ZUMO-VERSION:ZUMO/2.1 (lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
ZUMO-API-VERSION:2.0.0
ZUMO-API-VERSION:2.0.0
Response: OK
[]
Response: OK
[{"Id":"160714-070928-001","Name":"160714-070928-001","TableName":"DataFileDB","ParentId":"5f94574e-dea5-42b4-9aa2-66d7458c644f","ContentMD5":"iox4lgZG85hfNBswWcs7pw==","Length":4320,"LastModified":"2016-08-18T09:56:44+00:00","StoreUri":"/datafiledb-5f94574e-dea5-42b4-9aa2-66d7458c644f/160714-070928-001","Metadata":{}}]
'KM_Application.Windows.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Projects\LQSv2\LQS\KM_Application_Crossplatform\KM_Application.Windows\bin\x86\Debug\AppX\Microsoft.WindowsAzure.Mobile.Files.Ext.dll'. Cannot find or open the PDB file.
**Exception thrown: 'System.NullReferenceException' in Microsoft.WindowsAzure.Mobile.Files.Ext.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.ni.dll**
Exception thrown: 'System.NullReferenceException' in mscorlib.ni.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.ni.dll

I am using a PCL in combination with an UWP. To get the DownloadFileAsync-Method within the PCL working at all, I had to reference the netcore45/Microsoft.WindowsAzure.Mobile.Files.Ext.dll since the portable one is not available. 
The UWP required a reference to Microsoft.WindowsAzure.Mobile.Files (added the portable one).

**Comment by isamllr** [comment]
@pragnagopa 
Thanks, have been able to overcome the build errors.

Having issues with the Microsoft.Azure.Mobile.Client.Files.1.0.0-beta-2-160819\lib\net45\Microsoft.WindowsAzure.Mobile.Files.Ext.dll (referenced manually) - even if using WindowsAzure.Storage 7.2.0, it's looking for an old version:

`{"Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=6.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Das System kann die angegebene Datei nicht finden.":"Microsoft.WindowsAzure.Storage, Version=6.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}`


```
Request: POST https://lqs.azurewebsites.net/tables/DataFileDB/5f94574e-dea5-42b4-9aa2-66d7458c644f/StorageToken
{
  "Permissions": "Read",
  "TargetFile": {
    "Id": "160714-070928-001",
    "Name": "160714-070928-001",
    "TableName": "DataFileDB",
    "ParentId": "5f94574e-dea5-42b4-9aa2-66d7458c644f",
    "Length": 4320,
    "ContentMD5": "iox4lgZG85hfNBswWcs7pw==",
    "LastModified": "2016-08-18T11:56:44+02:00",
    "StoreUri": "/datafiledb-5f94574e-dea5-42b4-9aa2-66d7458c644f/160714-070928-001",
    "Metadata": {}
  },
  "ScopedEntityId": null,
  "ProviderName": null
}
HEADERS
X-ZUMO-FEATURES:AT
X-ZUMO-INSTALLATION-ID:2a7ca608-98d8-4dcc-bfcd-36f0e41579e3
Accept:application/json
User-Agent:ZUMO/2.1,(lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
X-ZUMO-VERSION:ZUMO/2.1 (lang=Managed; os=Windows Store; os_version=--; arch=X86; version=2.1.40803.0)
ZUMO-API-VERSION:2.0.0
Response: OK
{"RawToken":"?sv=2015-12-11&sr=c&sig=C9amnGU%2BNERqhc71%2FMBA2MtYTndpwkoLBQ1lEinBiuQ%3D&se=2016-08-30T16%3A02%3A36Z&sp=r","ResourceUri":"https://lqsstorage.blob.core.windows.net:443/datafiledb-5f94574e-dea5-42b4-9aa2-66d7458c644f","EntityId":"5f94574e-dea5-42b4-9aa2-66d7458c644f","Permissions":1,"Scope":0}
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.ni.dll
```


`
"   at Microsoft.WindowsAzure.MobileServices.Files.StorageProviders.AzureBlobStorageProvider.DownloadFileToStreamAsync(MobileServiceFile file, Stream stream, StorageToken storageToken)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.MobileServiceFilesClient.<DownloadToStreamAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.WindowsAzure.MobileServices.Files.MobileServiceSyncTableExtensions.<**DownloadFileAsync**>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at KM_Application.Core.Models.FileSyncHandler.<ProcessFileSynchronizationAction>d__7.MoveNext()"`

Config:

Packages.config PCL:
 
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CommonServiceLocator" version="1.3" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="Microsoft.Azure.Mobile.Client" version="2.0.1" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Azure.Mobile.Client.Files" version="1.0.0-beta-2-160819" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Azure.Mobile.Client.SQLiteStore" version="2.0.1" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Data.Edm" version="5.6.4" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Data.OData" version="5.6.4" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="portable45-net45+win8+wpa81" />
  <package id="MvvmLightLibs" version="5.3.0.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Newtonsoft.Json" version="9.0.1-beta1" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Nito.AsyncEx" version="3.0.1" targetFramework="portable45-net45+win8+wpa81" />
  <package id="OxyPlot.Core" version="1.0.0-unstable2176" targetFramework="portable45-net45+win8+wpa81" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="PCLStorage" version="1.0.2" targetFramework="portable45-net45+win8+wpa81" />
  <package id="PInvoke.BCrypt" version="0.3.2" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="PInvoke.Kernel32" version="0.3.2" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="PInvoke.NCrypt" version="0.3.2" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="PInvoke.Windows.Core" version="0.3.2" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="Portable.DataAnnotations" version="1.0.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Portable-Strong.DataAnnotations" version="1.0.1" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="rda.SocketsForPCL" version="1.2.2" targetFramework="portable-win81+wpa81" />
  <package id="Rx-Core" version="2.2.5" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="Rx-Interfaces" version="2.2.5" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="Rx-Linq" version="2.2.5" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="Rx-Main" version="2.2.5" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="Rx-PlatformServices" version="2.2.5" targetFramework="portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="SQLite.Net.Core-PCL" version="3.1.1" targetFramework="portable-net45+win+wpa81" />
  <package id="SQLite.Net-PCL" version="3.1.1" targetFramework="portable-net45+win+wpa81" />
  <package id="SQLiteNetExtensions" version="1.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="SQLitePCL" version="3.8.7.2" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Data.SQLite" version="1.0.101.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Spatial" version="5.6.4" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Validation" version="2.2.8" targetFramework="portable-net45+win+wpa81" />
  <package id="WindowsAzure.Storage" version="7.0.1-preview" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Xam.Plugins.Settings" version="2.1.0" targetFramework="portable-net45+win+wpa81" />
</packages>
 
Project.json UWP:
 
{
  "dependencies": {
    "Microsoft.ApplicationInsights": "2.2.0-beta1",
    "Microsoft.Azure.KeyVault.Core": "1.0.0",
    "Microsoft.Azure.Mobile.Client": "2.1.1",
    "Microsoft.Azure.Mobile.Client.SQLiteStore": "2.1.1",
    "Microsoft.Net.Http": "2.2.29",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.0",
    "MvvmLight": "5.3.0",
    "Newtonsoft.Json": "9.0.1-beta1",
    "Nito.AsyncEx": "3.0.1",
    "OxyPlot.Windows": "1.0.0-unstable2176",
    "PCLCrypto": "2.0.147",
    "PCLStorage": "1.0.2",
    "Portable.DataAnnotations": "1.0.0",
    "rda.SocketsForPCL": "1.2.2",
    "SQLite.Net-PCL": "3.1.1",
    "Syncfusion.Pdf.UWP46": "14.1.0.41",
    "System.Data.SQLite": "1.0.101",
    "WindowsStateTriggers": "1.1.0",
    "Xam.Plugins.Settings": "2.1.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
   "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by pragnagopa** [comment]
This looks like error due to mismatch in versions on the server. Thank you for reporting this. I will open an issue to track this.  As a workaround, can you use Microsoft.WindowsAzure.Storage, Version=6.1.1.0 on the Azure mobile server app?

**Comment by isamllr** [comment]
Unfortunately no difference.

**Comment by pragnagopa** [comment]
I cannot repro the issue if I have Microsoft.WindowsAzure.Storage, Version=6.1.1.0 on client and server. When you publish the server with reference to Microsoft.WindowsAzure.Storage, Version=6.1.1.0, can you check the box to Remove additional files at destination?
![publishremovefiles](https://cloud.githubusercontent.com/assets/1874279/18100912/94238570-6ea1-11e6-8f42-b6c9665640ad.png)

**Comment by isamllr** [comment]
Works when downgrading the client as well, did not do that in the first approach. Thanks!

There is still an exception thrown, but when catching the error we are fine...
Wonder if that's caused by the app design or the SDKs.

Exception:
"The process cannot access the file 'C:\\Users\\xyz\\AppData\\Local\\Packages\\appname6ycvr6vz3vtm\\LocalState\\160714-070928-001' because it is being used by another process."

Stacktrace:
"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.File.Create(String path)\r\n   at Microsoft.WindowsAzure.Mobile.Files.IO.File.CreateAsync(String targetPath)\r\n   at Microsoft.WindowsAzure.MobileServices.Files.MobileServiceSyncTableExtensions.<DownloadFileAsync>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at KM_Application.Core.Models.FileSyncHandler.<ProcessFileSynchronizationAction>d__7.MoveNext()"

**Comment by pragnagopa** [comment]
As the error indicates some process is holding on to the file. Try uninstalling the app, clean and rebuild solution.

**Comment by isamllr** [comment]
Solved the issue by applying @lindydonna s solution
